### ISSUE TITLE
Fails to compile on 5.8.5 -Duseithreads -Doptimize='-g' -DDEBUGGING on gcc5.3.1

### ISSUE THREAD

**Issue by ribasushi** [mhx/Devel-PPPort#31]
I am going to leave the entire log here, feel free to trim as needed.

```
Building and testing Devel-PPPort-3.32 ... cp PPPort.pm blib/lib/Devel/PPPort.pm
Running Mkbootstrap for Devel::PPPort ()
chmod 644 "PPPort.bs"
"/home/rabbit/perl5/perlbrew/perls/5.8.5_dbg/bin/perl" "-Iblib/arch" "-Iblib/lib" PPPort_xs.PL RealPPPort.xs
adding XS code from parts/inc/sv_xpvf
"/home/rabbit/perl5/perlbrew/perls/5.8.5_dbg/bin/perl" "/home/rabbit/perl5/perlbrew/perls/5.8.5_dbg/lib/5.8.5/ExtUtils/xsubpp" -noprototypes -typemap "/home/rabbit/perl5/perlbrew/perls/5.8.5_dbg/lib/5.8.5/ExtUtils/typemap" -typemap "typemap"  RealPPPort.xs > RealPPPort.xsc && mv RealPPPort.xsc RealPPPort.c
"/home/rabbit/perl5/perlbrew/perls/5.8.5_dbg/bin/perl" "-Iblib/arch" "-Iblib/lib" ppport_h.PL ppport.h
cc -c   -D_REENTRANT -D_GNU_SOURCE -DDEBUGGING -fno-strict-aliasing -pipe -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -g   -DVERSION=\"3.32\" -DXS_VERSION=\"3.32\" -fpic "-I/home/rabbit/perl5/perlbrew/perls/5.8.5_dbg/lib/5.8.5/x86_64-linux-thread-multi/CORE"   RealPPPort.c
In file included from RealPPPort.xs:31:0:
RealPPPort.c: In function ‘S_croak_xs_usage’:
/home/rabbit/perl5/perlbrew/perls/5.8.5_dbg/lib/5.8.5/x86_64-linux-thread-multi/CORE/perl.h:115:18: error: ‘my_perl’ undeclared (first use in this function)
 #    define aTHX my_perl
                  ^
/home/rabbit/perl5/perlbrew/perls/5.8.5_dbg/lib/5.8.5/x86_64-linux-thread-multi/CORE/perl.h:2619:40: note: in definition of macro ‘PERL_DEB’
 #  define PERL_DEB(a)                  a
                                        ^
/home/rabbit/perl5/perlbrew/perls/5.8.5_dbg/lib/5.8.5/x86_64-linux-thread-multi/CORE/perl.h:120:18: note: in expansion of macro ‘aTHX’
 #  define aTHX_  aTHX,
                  ^
/home/rabbit/perl5/perlbrew/perls/5.8.5_dbg/lib/5.8.5/x86_64-linux-thread-multi/CORE/perl.h:2773:17: note: in expansion of macro ‘aTHX_’
      Perl_croak(aTHX_ "Assertion " STRINGIFY(what) " failed: file \"%s\", line %d", \
                 ^
RealPPPort.c:423:41: note: in expansion of macro ‘assert’
 #define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)
                                         ^
RealPPPort.c:434:5: note: in expansion of macro ‘PERL_ARGS_ASSERT_CROAK_XS_USAGE’
     PERL_ARGS_ASSERT_CROAK_XS_USAGE;
     ^
/home/rabbit/perl5/perlbrew/perls/5.8.5_dbg/lib/5.8.5/x86_64-linux-thread-multi/CORE/perl.h:115:18: note: each undeclared identifier is reported only once for each function it appears in
 #    define aTHX my_perl
                  ^
/home/rabbit/perl5/perlbrew/perls/5.8.5_dbg/lib/5.8.5/x86_64-linux-thread-multi/CORE/perl.h:2619:40: note: in definition of macro ‘PERL_DEB’
 #  define PERL_DEB(a)                  a
                                        ^
/home/rabbit/perl5/perlbrew/perls/5.8.5_dbg/lib/5.8.5/x86_64-linux-thread-multi/CORE/perl.h:120:18: note: in expansion of macro ‘aTHX’
 #  define aTHX_  aTHX,
                  ^
/home/rabbit/perl5/perlbrew/perls/5.8.5_dbg/lib/5.8.5/x86_64-linux-thread-multi/CORE/perl.h:2773:17: note: in expansion of macro ‘aTHX_’
      Perl_croak(aTHX_ "Assertion " STRINGIFY(what) " failed: file \"%s\", line %d", \
                 ^
RealPPPort.c:423:41: note: in expansion of macro ‘assert’
 #define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)
                                         ^
RealPPPort.c:434:5: note: in expansion of macro ‘PERL_ARGS_ASSERT_CROAK_XS_USAGE’
     PERL_ARGS_ASSERT_CROAK_XS_USAGE;
     ^
Makefile:349: recipe for target 'RealPPPort.o' failed
make: *** [RealPPPort.o] Error 1

```

**Comment by ribasushi** [comment]
Closing - I stupidly assumed a problem, when this just happened to be the first XS module to be compiled.
So a fuckup of mine in a debugging frenzy, it's actually EU::ParseXS that doesn't work in this situation.

**Comment by wolfsage** [comment]
Reported against ExtUtils::ParseXS here: https://rt.perl.org/Ticket/Display.html?id=127739

**Comment by wolfsage** [comment]
Thanks!
